name: Deploy to Railway

on:
  push:
    branches:
      - main  # Despliega cuando haya cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Distribución de OpenJDK por defecto
          java-version: '17'  # Configura Java 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Agrega tu token de Railway en los secretos de GitHub
        run: |
          railway up --detach  # Despliega el proyecto en Railway en modo desatendido
